phraseapp:
  access_token: "55aaaaca15b1128b8d9943766163999add8392ff7d449781176ecf234f47c924"
  project_id: "0c583679ebf1e4e8e6a6f917c31f7cd1"
  file_format: "yml"
  push:
    sources:
    - file: "./src/locales/*.json"
  pull:
    targets:
    - file: "./src/locales/<locale_name>.json"