version: "2"
services:
  electron_server:
    image: node:8
    ports:
    - 5500:5500
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn start:prod'
    depends_on:
    - db
    environment:
    - NODE_ENV=production
    - DATABASE_URL=postgres://postgres:password@db:5432/relthub
    - PORT=5500
    - S3_KEY=AYN4EVFWKFB2TSX2WLFX
    - S3_SECRET=KfYRDaoQPfJsA4dEsPF1PanU+OWF32sqvKJpbffqODI
    - S3_ENDPOINT=ams3.digitaloceanspaces.com
    - S3_BUCKET=content-realthub-com
    - AUTH_POLICY_EXPIRES=2592000
    - AUTH_POLICY_SECRET=_wox8l^asoshLKHklh3kejlndlsdj
    - DATABASE_SSL=false
  db:
    image: postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=realthub
